# Generated by Django 5.1.4 on 2025-02-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userdetails_goal_alter_userprofile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='training_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Int ermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
