# Generated by Django 5.1.4 on 2025-02-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_training_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
