# Generated by Django 5.1.6 on 2025-02-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userdetails_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'user information', 'verbose_name_plural': 'user information'},
        ),
    ]
