# Generated by Django 5.1.6 on 2025-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
