# Generated by Django 5.1.4 on 2025-02-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_fooditem_carbs_fooditem_fats_fooditem_protein_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfoodlog',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='userfoodlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='UserFoodLog',
        ),
    ]
