# Generated by Django 5.1.6 on 2025-02-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0003_remove_userfoodlog_food_item_remove_userfoodlog_user_and_more'),
        ('users', '0010_alter_userdetails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaloricIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
            ],
        ),
    ]
