# Generated by Django 5.1.4 on 2025-02-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='video_id',
        ),
        migrations.AddField(
            model_name='workout',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='workout',
            name='goal',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Gain Muscle', 'Gain Muscle'), ('Maintain', 'Maintain Weight')], default='Maintain Weight', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='training_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/embed/yPK7ISPEu3M?si=5RFvWFVHYDtdVjnb'),
        ),
        migrations.AddField(
            model_name='workout',
            name='week_number',
            field=models.IntegerField(default=1, help_text='Week number (1, 2, 3, etc.)'),
        ),
    ]
