# Generated by Django 5.1.6 on 2025-02-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_remove_workout_duration_workout_max_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='workout',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='workout',
            name='repeat_every_n_weeks',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
