# Generated by Django 5.1.6 on 2025-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_workout_week_number_workout_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='repeat_every_n_weeks',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='workout',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='repeat_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='goal',
            field=models.CharField(choices=[('lose-weight', 'Lose Weight'), ('gain-muscle', 'Gain Muscle'), ('maintain', 'Maintain Weight')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='max_weight',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='min_weight',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='workout',
            name='training_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50),
        ),
        migrations.DeleteModel(
            name='UserWorkoutSchedule',
        ),
    ]
