# Generated by Django 5.1.6 on 2025-02-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_workout_day_of_week_alter_workout_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='week_number',
        ),
        migrations.AddField(
            model_name='workout',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='workouts/videos/'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
