# Generated by Django 5.1.6 on 2025-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_remove_workout_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='repeat_days',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='workout',
            name='goal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workout',
            name='repeat_interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='training_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='workouts/'),
        ),
    ]
