# Generated by Django 5.1.6 on 2025-02-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_workout_repeat_days_alter_workout_goal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='repeat_interval',
            new_name='repeat_interval_weeks',
        ),
    ]
