# Generated by Django 5.1.6 on 2025-02-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_rename_repeat_interval_workout_repeat_interval_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
